Added Kitchen tests and travis
salt-formulas/salt-formula-galera pull request #24
Opened 2017-04-11 12:57 UTC by Martin819

2017-04-11 12:57 UTC, cloudlab-autobuild commented
Can one of the admins verify this patch?

2017-04-21 17:58 UTC, fpytloun requested changes

2017-04-21 17:58 UTC, fpytloun commented on galera/master.sls
> +  {%- if not grains.get('noservices','false')%}
Should default to boolean False. The same bellow.

2017-05-02 09:19 UTC, epcim commented
@Martin819 poslal jsem ti PR na branch ktery to fixne. Jinak +1

2017-05-02 09:21 UTC, epcim commented on galera/map.jinja
> +    'pkgs': ['mysql-wsrep-5.6', 'galera-3', 'rsync', 'python-mysqldb', 'psmisc', 'netcat', 'percona-xtrabackup', 'socat', 'libdbd-mysql', 'python-pymysql'],
do I understand that current formula has wrong pkg name? mysql-server-wsrep ..  Pls explain.

2017-05-04 07:36 UTC, Martin819 commented on galera/map.jinja
> +    'pkgs': ['mysql-wsrep-5.6', 'galera-3', 'rsync', 'python-mysqldb', 'psmisc', 'netcat', 'percona-xtrabackup', 'socat', 'libdbd-mysql', 'python-pymysql'],
Yes, exactly. The name has changed.

2017-05-17 11:59 UTC, Martin819 commented
@fpytloun can you plese recheck?

2017-05-18 12:19 UTC, merged