Split brain clustercheck
salt-formulas/salt-formula-galera pull request #27
Opened 2017-05-22 15:53 UTC by TomasHradecky

splitbrain condition through xinetd and clustercheck script [WIP]

2017-05-22 15:53 UTC, cloudlab-autobuild commented
Can one of the admins verify this patch?

2017-05-22 18:55 UTC, epcim commented on galera/slave.sls
> +
do not edit this file - I will remove

2017-05-23 13:51 UTC, epcim commented
also add's additional user setup, same way we introduced in: https://github.com/salt-formulas/salt-formula-mysql/pull/9

2017-05-23 16:04 UTC, pupapaik commented
Please wait until my verification before we merge this change.

2017-05-23 22:04 UTC, epcim requested changes
fix minors, extend test... I will test it before the merge.
actual merge is not a problem, as not enabled by default, but we have to keep an eye before we merge the counterpart patch to reclass system-level.

2017-05-23 22:04 UTC, epcim commented on tests/integration/slave_cluster/checks_clustercheck_spec.rb
> +describe file('/etc/xinetd.d/mysql_clustercheck_9200') do
clustercheck.conf

2017-05-23 22:04 UTC, epcim commented on tests/integration/master_cluster/checks_clustercheck_spec.rb
> +    its('content') { should match /clustercheck password clustercheck 1 1/ }
I was wrong here... (trap for @TomasHradecky) we should match "clustercheck clustercheck password" the user/password are switched

2017-05-29 09:01 UTC, epcim commented
closing in favor of squashed PR#30

2017-05-29 13:01 UTC, closed without merging